version: "3.2"
services:
  flask:
    build:
      context: ./
    image: myflasktest
    logging: &loggingDriver
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    container_name: flask
    #networks:
    #  - znetwork
    volumes:
      - ./app:/usr/src/app
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lp_zarva_me.tls=true"
        - "traefik.http.routers.lp_zarva_me.entryPoints=websecure"
        - "traefik.http.routers.lp_zarva_me.rule=Host(`lp.zarva.me`, `www.lp.zarva.me`)"
        - "traefik.http.services.lp_zarva_me.loadbalancer.server.port=80"
        - "traefik.http.routers.http_lp_zarva_me.entryPoints=web"
        - "traefik.http.routers.http_lp_zarva_me.rule=Host(`lp.zarva.me`, `www.lp.zarva.me`)"
        - "traefik.http.routers.http_lp_zarva_me.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectScheme.scheme=https"